language: python

python: "3.6"

# don't clone more than necessary
git:
  depth: 1

# Install the codecov pip dependency
install:
  - pip install codecov

# script to run tests. Can also use make, e.g. "make test"
script: 
  - coverage run -m unittest discover -p "*_test.py"

after_success:
  - codecov